<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1QFEABf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1QFEABf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1QFEABf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1QFEABf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1QFEABf\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => '1QFEABf',
    'container.build_id' => '55692ab9',
    'container.build_time' => 1547744879,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1QFEABf');
