<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerClUiC8m\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerClUiC8m/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerClUiC8m.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerClUiC8m\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerClUiC8m\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'ClUiC8m',
    'container.build_id' => '5ddea22e',
    'container.build_time' => 1548866974,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerClUiC8m');
