<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bCDcyYD' shared service.

return $this->privates['.service_locator.bCDcyYD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'twigEnvironment' => array('services', 'twig', 'getTwigService', false),
));
