<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFVJazbB\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFVJazbB/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFVJazbB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFVJazbB\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerFVJazbB\srcApp_KernelProdContainer(array(
    'container.build_hash' => 'FVJazbB',
    'container.build_id' => '97b2daef',
    'container.build_time' => 1548849631,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFVJazbB');
