<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.q0UqyxM' shared service.

return $this->privates['.service_locator.q0UqyxM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'cache' => array('services', 'cache.app', 'getCache_AppService', false),
    'markdown' => array('services', 'markdown.parser', 'getMarkdown_ParserService', false),
));
