<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\service\MarkdownHelper' shared autowired service.

include_once $this->targetDirs[3].'/src/service/MarkdownHelper.php';

return $this->privates['App\service\MarkdownHelper'] = new \App\service\MarkdownHelper(($this->services['monolog.logger.markdown'] ?? $this->load('getMonolog_Logger_MarkdownService.php')));
