<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4WY7HTm' shared service.

return $this->privates['.service_locator.4WY7HTm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'isDebug' => array('privates', '.value.C_5.39h', 'get_Value_C5_39hService.php', true),
    'markdownHelper' => array('privates', 'App\\service\\MarkdownHelper', 'getMarkdownHelperService.php', true),
));
